export const ADMIN_EVENTS_COPY = {
  LIST_TITLE: 'Events',
  LIST_DESCRIPTION: 'Review events submitted by organisers awaiting approval.',
  LIST_DESCRIPTION_ACCEPTED: 'Events that have been approved and published.',
  LIST_DESCRIPTION_REJECTED: 'Events that were rejected during review.',
  LIST_LOADING: 'Loading events…',
  LIST_ERROR: 'Could not load events.',
  LIST_RETRY: 'Try again',
  TABS_ARIA_LABEL: 'Event review status',
  TAB_PENDING: 'Pending',
  TAB_ACCEPTED: 'Accepted',
  TAB_REJECTED: 'Rejected',
  TABLE_EMPTY_PENDING: 'No events pending approval.',
  TABLE_EMPTY_ACCEPTED: 'No accepted events.',
  TABLE_EMPTY_REJECTED: 'No rejected events.',
  DETAIL_LOADING: 'Loading event…',
  DETAIL_ERROR: 'Could not load this event.',
  DETAIL_RETRY: 'Try again',
  NOT_FOUND_TITLE: 'Event not found',
  NOT_FOUND_DESCRIPTION: 'This event may have been reviewed already or the link is invalid.',
  BACK_TO_EVENTS: 'Back to events',
  TABLE_EMPTY: 'No events pending approval.',
  TABLE_ORGANISER_COLUMN: 'Organiser',
  TABLE_EVENT_COLUMN: 'Event',
  TABLE_DATE_COLUMN: 'Start date',
  TABLE_ACTIONS_COLUMN: 'Actions',
  APPROVE_ACTION: 'Approve',
  REJECT_ACTION: 'Reject',
  APPROVE_SUCCESS: 'Event approved successfully.',
  REJECT_SUCCESS: 'Event rejected successfully.',
  ACTION_ERROR: 'Something went wrong. Please try again.',
  REJECT_DIALOG_TITLE: 'Reject event',
  REJECT_DIALOG_DESCRIPTION_PREFIX: 'Provide a reason for rejecting',
  REJECT_DIALOG_DESCRIPTION_SUFFIX: '. This will be shared with the organiser.',
  REJECT_DIALOG_CLOSE: 'Close reject dialog',
  REJECT_REASON_LABEL: 'Rejection reason',
  REJECT_REASON_PLACEHOLDER: 'Explain why this event cannot be approved…',
  REJECT_DIALOG_CANCEL: 'Cancel',
  REJECT_DIALOG_SUBMIT: 'Reject event',
  REJECT_DIALOG_SUBMITTING: 'Rejecting…',
  DETAIL_OVERVIEW_TITLE: 'Overview',
  DETAIL_ORGANISER_LABEL: 'Organiser',
  DETAIL_STATUS_LABEL: 'Status',
  DETAIL_SUBMITTED_LABEL: 'Submitted',
  DETAIL_SLUG_LABEL: 'Slug',
  DETAIL_DESCRIPTION_LABEL: 'Description',
  DETAIL_SESSIONS_TITLE: 'Sessions',
  DETAIL_NO_SESSIONS: 'No sessions configured.',
  DETAIL_TICKETS_TITLE: 'Ticket types',
  DETAIL_MEDIA_TITLE: 'Media',
  DETAIL_BANNER_LABEL: 'Banner',
  DETAIL_GALLERY_LABEL: 'Gallery',
  DETAIL_NO_TICKETS: 'No ticket types configured.',
  DETAIL_NO_MEDIA: 'No media uploaded.',
  DETAIL_LOCATION_VENUE: 'Venue',
  DETAIL_LOCATION_ONLINE: 'Online',
  DETAIL_LOCATION_RECORDED: 'Recorded',
  DETAIL_START_LABEL: 'Starts',
  DETAIL_END_LABEL: 'Ends',
  STATUS_PENDING_APPROVAL: 'Pending approval',
  STATUS_PUBLISHED: 'Published',
  STATUS_APPROVED: 'Approved',
  STATUS_REJECTED: 'Rejected',
  STATUS_DRAFT: 'Draft',
} as const
